### ISSUE TITLE
crates release?

### ISSUE THREAD

**Issue by madninja** [Nullus157/bs58-rs#100]
Could I ask for a release and crates.io publish to pick up the sha2 changes? It'll avoid a few duplicate crates in constrained environments downstream

**Comment by benma** [comment]
Seconded - please make a new release.

**Comment by daira** [comment]
+1. https://github.com/zcash/librustzcash/issues/757

**Comment by nuttycom** [comment]
bumping this to vote for it, please make a new release!

**Comment by Nemo157** [comment]
I have finally gotten around to publishing 0.5.0, this is a breaking change to fix #77 and renames a method, but should be trivial upgrade for most uses.
